---
# SPDX-FileCopyrightText: 2023 Felix Wege, EONERC-ACS, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

devices:
  - uid: umg-acs-lab
    # Optional name and description of the device
    name: Janitza UMG 801
    description: Measurement device in ACS laboratory

    # OPC-UA server address and port
    uri: janitza-umg.acs-lab.eonerc.rwth-aachen.de
    port: 4840

    # Number of samples per second (currently unsupported)
    sample_rate: 100.0

    # Measurement names need to be one of the allowed OPC-UA objects
    # U1 = Voltage LN1
    # U2 = Voltage LN2
    # U3 = Voltage LN3
    # Freq = System frequency
    #
    # Allowed types are: voltage, current, frequency
    measurements:
      U1:
        type: voltage
        momentary: true
        min: true
        max: true
      U2:
        type: voltage
        momentary: true
        min: true
        max: false
      U3:
        type: voltage
        momentary: true
        min: false
        max: false
      Freq:
        type: frequency
        momentary: true
