# SPDX-FileCopyrightText: 2024 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

[project]
name = "seguro-gateway"
version = "0.1.0"
description = ""
authors = [
  { name = "Felix Wege", email = "felix.wege@eonerc.rwth-aachen.de" },
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "asyncua==1.0.4",
  "pyyaml>=6.0.1",
  "schema>=0.7.5",
  "cryptography==42.0.5",
]

[project.urls]
Homepage = "https://github.com/SEGuRo-Projekt/Gateway"
"Bug Tracker" = "https://github.com/SEGuRo-Projekt/Gateway/issues"

[project.scripts]
opcua-readout = "seguro.gateway.opc_ua.readout:main"
opcua-mockup = "seguro.gateway.opc_ua.mockup:main"

[dependency-groups]
dev = [
  "flake8==6.0.0",
  "pre-commit==3.3.1",
]

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["seguro"]

[tool.black]
line-length = 79
